---
title: "p8105_hw6_bl2898"
author: "Boqian Li"
date: "12/3/2021"
output: html_document
---
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(broom)
library(ggpubr)
```

## Problem 1
Load and clean the data for regression analysis (i.e. convert numeric to factor where appropriate, check for missing data, etc.).
```{r}
clean_df <- read.csv("birthweight.csv") 
clean_df <- janitor::clean_names(clean_df) %>% 
  mutate(
    babysex = recode(babysex, `1` = "male", `2` = "female"),
    frace = recode(frace, `1` = "White", `2` = "Black", `3` = "Asian", `4` = "Puerto Rican", `8` = "Other", `9` = "Unknown"),
    malform = recode(malform, `0` = "absent", `1` = "present"),
    mrace = recode(mrace, `1` = "White", `2` = "Black", `3` = "Asian", `4` = "Puerto Rican", `8` = "Other"),
    babysex = factor(babysex),
    frace = factor(frace),
    mrace = factor(mrace),
    malform = factor(malform)
  )
clean_df
```

```{r}

```


## Problem 2
```{r}
library(tidyverse)
library(rnoaa)
library(broom)

weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())


dt <- data.frame(cbind(id = 1:nrow(weather_df),
                       tmax = weather_df$tmax,
                       tmin = weather_df$tmin))


r_sqr <- NULL
log_beta01 <- NULL
for (i in 1:5000){
  set.seed(i + 2021)
  
  boot_dt <- dt[sample(dt$id, replace = TRUE), ]
  
  lm_temp <- lm(tmax ~ tmin, data = boot_dt)
  
  r_sqr[i] <- as.numeric(broom::glance(lm_temp)[,1])
  
  beta0 <- as.numeric(broom::tidy(lm_temp)[1,2])
  beta1 <- as.numeric(broom::tidy(lm_temp)[2,2])
  log_beta01[i] <- log(beta0*beta1)
  
}

#distribution
hist(r_sqr)
hist(log_beta01)

#CI
param1_CI <- quantile(r_sqr, probs= c(0.025,0.975))
param1_CI
param2_CI <- quantile(log_beta01, probs = c(0.025,0.975))
param2_CI
```


